### ISSUE TITLE
Create a simulation to demonstrate reading data from the ISC 9000

### ISSUE THREAD

**Issue by Potato-Man114** [jak103/powerscore#16]
Jacob already created some code in the `backend` directory that can read signals from the ISC device. Create an automated simulation in Go that demonstrates ingesting that data and updating the live web pages (both scorekeeper and live game pages).

**Comment by Potato-Man114** [comment]
I've been working on this ticket. I won't have something demonstratable today, but I'll have it done soon. Dealing with serial ports is more of a struggle than I had hoped.

**Comment by jebidiah252** [comment]
> I've been working on this ticket. I won't have something demonstratable today, but I'll have it done soon. Dealing with serial ports is more of a struggle than I had hoped.

Sounds good. Hopefully I can get you some data for this and #6.

**Comment by Potato-Man114** [comment]
@jebidiah252 There is data at https://github.com/jak103/powerscore/blob/main/backend/output.txt that I have been able to use. Though it it is not a lot of data, I am not blocked. I'm working on documenting the data format so that we can create custom data from scratch to test with if need be.
