### ISSUE TITLE
iPad Application

### ISSUE THREAD

**Issue by jebidiah252** [jak103/powerscore#25]
We'll need to create an iPad application that will receive events from the powerscore web server. This app will be for the statisticians to input which player scored a goal and who assisted with it. We'll need to handle several use cases with this app. My thought is that this issue will be more of an Epic, rather than a standard issue.

**Comment by clickclackclark** [comment]
This is probably where I will be the most effective but I'm happy to work on something else if needed as well. I feel like I have a pretty solid idea of what needs to be done after talking with Jacob and seeing the diagram you provided on slack @jebidiah252

**Comment by clickclackclark** [comment]
I have a pull request incoming for this. Didn't get as far as I would have liked, however I tried to at least give directions via TODOs on where my thought process was to make it easier if someone else ends up taking a look at this and wants to use/reuse anything.

**Comment by clickclackclark** [comment]
Additional TODOs after the demo today:
* Need to handle team selection for adding a new penalty and new goal.
  * Could be an additional form dropdown, or could have separate buttons for each team.
* Ability to update the timer, if this information can't be retrieved from the rink.
