### ISSUE TITLE
Migrate Existing Live Game Frontend into a Vue Project.

### ISSUE THREAD

**Issue by jebidiah252** [jak103/powerscore#5]
We need to take the current `index.html` that exists in the `frontend` directory, and update it to work with a Vue project. There is a lot of content there already that exists for us to use in terms of HTML and CSS, all we would need to do is migrate it.

**Comment by Potato-Man114** [comment]
It won't let me assign myself to this task, so I'm using the all-powerful and most respected system to take this ticket.


![Image](https://github.com/jak103/powerscore/assets/97547996/33eba431-982e-4b50-b379-51e6ddd9be3f)

**Comment by clickclackclark** [comment]
Going to need Vue installed for [this one](https://github.com/jak103/powerscore/issues/4) as well, @Potato-Man114 let me know if there is anything I can help out with getting that set up (assuming both the live game and score keeper UIs will use the same Vue root and just be located at different routes, someone correct me if I'm wrong).

**Comment by Potato-Man114** [comment]
@clickclackclark Sounds good to me. I'll put the live game scoreboard at "/scoreboard". I've already created a vue project and started developing it. Can we meet tomorrow after class and discuss this further?
